<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Semester_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get semester by id
     */
    function get_semester($id)
    {
        return $this->db->get_where('semesters', array('id' => $id))->row_array();
    }

    /*
     * Get all semesters
     */
    function get_all_semesters()
    {
        $this->db->order_by('id', 'asc');
        return $this->db->get('semesters')->result_array();
    }

    /*
     * function to add new semester
     */
    function add_semester($params)
    {
        $this->db->insert('semesters', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update semester
     */
    function update_semester($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('semesters', $params);
    }

    /*
     * function to delete semester
     */
    function delete_semester($id)
    {
        return $this->db->delete('semesters', array('id' => $id));
    }
}
