<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Stream_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get stream by id
     */
    function get_stream($id)
    {
        return $this->db->get_where('streams', array('id' => $id))->row_array();
    }

    /*
     * Get all streams
     */
    function get_all_streams()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('streams')->result_array();
    }

    /*
     * function to add new stream
     */
    function add_stream($params)
    {
        $this->db->insert('streams', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update stream
     */
    function update_stream($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('streams', $params);
    }

    /*
     * function to delete stream
     */
    function delete_stream($id)
    {
        return $this->db->delete('streams', array('id' => $id));
    }
}
